// Datos iniciales de Mi Despensa: recetas rápidas, catálogo de productos y sugerencias.
// Las calorías son aproximadas por porción.

const CATEGORIAS = {
  carnes: { nombre: 'Carnes y embutidos', tipo: 'comida' },
  congelados: { nombre: 'Congelados', tipo: 'comida' },
  verduras: { nombre: 'Frutas y verduras que duran', tipo: 'comida' },
  lacteos: { nombre: 'Lácteos', tipo: 'comida' },
  panaderia: { nombre: 'Tortillas y pan', tipo: 'comida' },
  alacena: { nombre: 'Alacena', tipo: 'comida' },
  latas: { nombre: 'Latas y conservas', tipo: 'comida' },
  salsas: { nombre: 'Salsas y condimentos', tipo: 'comida' },
  desayuno: { nombre: 'Desayuno y botanas', tipo: 'comida' },
  bebidas: { nombre: 'Bebidas', tipo: 'comida' },
  aseoPersonal: { nombre: 'Aseo personal', tipo: 'aseo' },
  limpieza: { nombre: 'Limpieza del hogar', tipo: 'aseo' },
  otros: { nombre: 'Otros', tipo: 'otro' },
};

// Recetas pensadas para un mercado mensual: congelados, latas y verduras que aguantan.
const ing = (nombre, cat) => ({ nombre, cat });

const RECETAS_BASE = [
  {
    id: 'tacos-carne', nombre: 'Tacos de carne molida', minutos: 12, kcal: 550,
    ingredientes: [ing('Carne molida de res', 'carnes'), ing('Tortillas de maíz', 'panaderia'), ing('Cebolla', 'verduras'), ing('Limones', 'verduras'), ing('Salsa verde (frasco)', 'salsas')],
    pasos: ['Dora la carne (descongelada) con cebolla picada y sal, 8 min.', 'Calienta las tortillas.', 'Sirve con limón y salsa.'],
  },
  {
    id: 'bistec-papas', nombre: 'Bistec con papas', minutos: 12, kcal: 600,
    ingredientes: [ing('Bistec de res', 'carnes'), ing('Papas', 'verduras'), ing('Cebolla', 'verduras'), ing('Aceite', 'alacena')],
    pasos: ['Corta la papa en cubitos y métela 5 min al microondas.', 'Dórala en sartén con aceite y cebolla.', 'Cocina el bistec 2–3 min por lado.'],
  },
  {
    id: 'bowl-atun', nombre: 'Bowl de atún con elote', minutos: 5, kcal: 520,
    ingredientes: [ing('Arroz', 'alacena'), ing('Atún en lata', 'latas'), ing('Elote en lata', 'latas'), ing('Mayonesa', 'salsas'), ing('Chiles chipotles en lata', 'latas')],
    pasos: ['Calienta una porción de arroz ya cocido.', 'Mezcla mayonesa con un poco de chipotle.', 'Arma el bowl con atún y elote.'],
  },
  {
    id: 'quesadillas-chorizo', nombre: 'Quesadillas de chorizo con papa', minutos: 12, kcal: 650, tags: ['cerdo'],
    ingredientes: [ing('Chorizo', 'carnes'), ing('Papas', 'verduras'), ing('Tortillas de maíz', 'panaderia'), ing('Queso Oaxaca', 'lacteos')],
    pasos: ['Papa en cubitos 4 min al microondas.', 'Fríe el chorizo y mezcla con la papa.', 'Rellena las tortillas con queso y el guiso, y dóralas.'],
  },
  {
    id: 'arroz-carne', nombre: 'Arroz con carne molida y verduras', minutos: 10, kcal: 600,
    ingredientes: [ing('Arroz', 'alacena'), ing('Carne molida de res', 'carnes'), ing('Verduras mixtas congeladas', 'congelados'), ing('Salsa de soya', 'salsas')],
    pasos: ['Saltea las verduras congeladas 4 min.', 'Agrega la carne y el arroz ya cocido.', 'Sazona con soya y mezcla 3 min.'],
  },
  {
    id: 'chuleta-brocoli', nombre: 'Chuleta de cerdo con brócoli', minutos: 12, kcal: 500, tags: ['cerdo'],
    ingredientes: [ing('Chuletas de cerdo', 'carnes'), ing('Brócoli congelado', 'congelados'), ing('Ajo en polvo', 'salsas'), ing('Aceite', 'alacena')],
    pasos: ['Sazona la chuleta con sal y ajo y cocínala 4 min por lado.', 'Mientras, cuece el brócoli 4 min en el microondas con un poco de agua.'],
  },
  {
    id: 'tostadas-atun', nombre: 'Tostadas de atún', minutos: 5, kcal: 400,
    ingredientes: [ing('Tostadas', 'panaderia'), ing('Atún en lata', 'latas'), ing('Cebolla', 'verduras'), ing('Limones', 'verduras'), ing('Salsa picante', 'salsas')],
    pasos: ['Mezcla el atún con cebolla picada, limón y salsa.', 'Sirve sobre las tostadas.'],
  },
  {
    id: 'tacos-champinon', nombre: 'Tacos de queso con champiñones', minutos: 10, kcal: 450,
    ingredientes: [ing('Queso Oaxaca', 'lacteos'), ing('Champiñones en lata', 'latas'), ing('Cebolla', 'verduras'), ing('Tortillas de maíz', 'panaderia'), ing('Salsa verde (frasco)', 'salsas')],
    pasos: ['Saltea los champiñones escurridos con cebolla.', 'Agrega queso y deja que se derrita.', 'Arma los tacos con salsa.'],
  },
  {
    id: 'sandwich-jamon', nombre: 'Sándwich caliente de jamón y queso', minutos: 7, kcal: 450, tags: ['cerdo'],
    ingredientes: [ing('Pan de caja', 'panaderia'), ing('Jamón', 'carnes'), ing('Queso amarillo rebanado', 'lacteos')],
    pasos: ['Arma el sándwich (el pan puede ir directo del congelador).', 'Dóralo en sartén con tapa 3 min por lado.'],
  },
  {
    id: 'picadillo', nombre: 'Picadillo con arroz', minutos: 12, kcal: 600,
    ingredientes: [ing('Carne molida de res', 'carnes'), ing('Papas', 'verduras'), ing('Verduras mixtas congeladas', 'congelados'), ing('Puré de tomate', 'latas'), ing('Arroz', 'alacena')],
    pasos: ['Papa en cubitos, 5 min al microondas.', 'Cocina la carne, agrega las verduras congeladas, la papa y el puré.', 'Sirve con arroz.'],
  },
  {
    id: 'burrito-carne', nombre: 'Burrito de carne molida', minutos: 10, kcal: 700,
    ingredientes: [ing('Tortillas de harina', 'panaderia'), ing('Carne molida de res', 'carnes'), ing('Arroz', 'alacena'), ing('Queso Oaxaca', 'lacteos'), ing('Chiles chipotles en lata', 'latas')],
    pasos: ['Calienta carne y arroz.', 'Rellena la tortilla con queso y chipotle, enrolla y dora 1 min.'],
  },
  {
    id: 'pasta-tomate', nombre: 'Pasta con salsa de tomate', minutos: 15, kcal: 600,
    ingredientes: [ing('Pasta', 'alacena'), ing('Puré de tomate', 'latas'), ing('Queso parmesano', 'lacteos')],
    pasos: ['Cuece la pasta 10 min.', 'Calienta el puré con sal y ajo, mezcla y sirve con queso.'],
  },
  {
    id: 'pasta-bolonesa', nombre: 'Pasta boloñesa rápida', minutos: 15, kcal: 720,
    ingredientes: [ing('Pasta', 'alacena'), ing('Carne molida de res', 'carnes'), ing('Puré de tomate', 'latas'), ing('Ajo en polvo', 'salsas'), ing('Queso parmesano', 'lacteos')],
    pasos: ['Cuece la pasta 10 min.', 'Mientras, dora la carne y agrega el puré, sal y ajo.', 'Mezcla y sirve con queso.'],
  },
  {
    id: 'ensalada-pasta-atun', nombre: 'Ensalada de pasta con atún', minutos: 12, kcal: 600,
    ingredientes: [ing('Pasta', 'alacena'), ing('Atún en lata', 'latas'), ing('Elote en lata', 'latas'), ing('Mayonesa', 'salsas')],
    pasos: ['Cuece la pasta y enjuágala con agua fría.', 'Mezcla con atún, elote y mayonesa. Sobra para el día siguiente.'],
  },
  {
    id: 'salchichas-mexicana', nombre: 'Salchichas a la mexicana', minutos: 10, kcal: 550,
    ingredientes: [ing('Salchichas', 'carnes'), ing('Cebolla', 'verduras'), ing('Puré de tomate', 'latas'), ing('Chiles en vinagre', 'latas'), ing('Tortillas de maíz', 'panaderia')],
    pasos: ['Corta las salchichas y dóralas con cebolla.', 'Agrega puré de tomate y chiles en vinagre picados, 3 min.', 'Sirve con tortillas.'],
  },
  {
    id: 'hamburguesa', nombre: 'Hamburguesa con papas', minutos: 15, kcal: 850,
    ingredientes: [ing('Hamburguesas de res congeladas', 'congelados'), ing('Pan para hamburguesa', 'panaderia'), ing('Queso amarillo rebanado', 'lacteos'), ing('Papas a la francesa congeladas', 'congelados'), ing('Catsup', 'salsas'), ing('Mostaza', 'salsas')],
    pasos: ['Hornea o fríe las papas congeladas (12 min).', 'Cocina la carne 4 min por lado, pon el queso encima.', 'Arma con el pan tostado.'],
  },
  {
    id: 'milanesa-pure', nombre: 'Milanesa de res con puré', minutos: 12, kcal: 650,
    ingredientes: [ing('Milanesas de res empanizadas', 'carnes'), ing('Puré de papa instantáneo', 'alacena'), ing('Leche larga vida', 'lacteos'), ing('Aceite', 'alacena')],
    pasos: ['Fríe la milanesa 3 min por lado.', 'Prepara el puré instantáneo con leche caliente.'],
  },
  {
    id: 'sopa-fideo', nombre: 'Sopa de fideo con verduras', minutos: 12, kcal: 400,
    ingredientes: [ing('Sopa de fideo', 'alacena'), ing('Puré de tomate', 'latas'), ing('Caldo de res en cubo', 'salsas'), ing('Verduras mixtas congeladas', 'congelados')],
    pasos: ['Dora el fideo en poco aceite.', 'Agrega puré, agua, el cubo de caldo y las verduras.', 'Hierve 8 min.'],
  },
  {
    id: 'arroz-chorizo', nombre: 'Arroz con chorizo y elote', minutos: 10, kcal: 650, tags: ['cerdo'],
    ingredientes: [ing('Arroz', 'alacena'), ing('Chorizo', 'carnes'), ing('Elote en lata', 'latas')],
    pasos: ['Fríe el chorizo.', 'Agrega el arroz ya cocido y el elote, mezcla 3 min.'],
  },
  {
    id: 'pescado-empanizado', nombre: 'Pescado empanizado con verduras', minutos: 15, kcal: 550, tags: ['pescado'],
    ingredientes: [ing('Filetes de pescado empanizado congelados', 'congelados'), ing('Verduras mixtas congeladas', 'congelados'), ing('Limones', 'verduras')],
    pasos: ['Hornea o fríe el pescado directo del congelador (12 min).', 'Cuece las verduras en el microondas 4 min.', 'Sirve con limón.'],
  },
];

// Catálogo de productos. q = cantidad sugerida para un mes (1 persona).
// mes = 1 → entra en la lista "Mercado del mes" recomendada.
const prod = (n, c, q = '', mes = 0, nota = '') => ({ n, c, q, mes: !!mes, nota });

const CATALOGO = [
  // Carnes: se congelan en porciones
  prod('Carne molida de res', 'carnes', '3 kg', 1, 'Congela en bolsas de 250 g'),
  prod('Bistec de res', 'carnes', '1.5 kg', 1, 'Congela en porciones'),
  prod('Chuletas de cerdo', 'carnes', '1 kg', 1, 'Congela en porciones'),
  prod('Milanesas de res empanizadas', 'carnes', '1 kg', 1, 'Congela separadas con plástico'),
  prod('Chorizo', 'carnes', '4 piezas', 1, 'Congela'),
  prod('Salchichas', 'carnes', '2 paquetes', 1, 'Congela uno'),
  prod('Jamón', 'carnes', '2 paquetes', 1, 'Congela uno'),
  prod('Tocino', 'carnes', '1 paquete'),
  prod('Carne para asar', 'carnes', '1 kg'),
  prod('Costillas de cerdo', 'carnes', '1 kg'),
  prod('Carne al pastor', 'carnes', '1 kg'),
  prod('Arrachera', 'carnes', '1 kg'),
  prod('Filete de pescado', 'carnes', '1 kg'),
  prod('Pepperoni', 'carnes', '1 paquete'),
  prod('Salami', 'carnes', '1 paquete'),

  // Congelados
  prod('Verduras mixtas congeladas', 'congelados', '4 bolsas', 1),
  prod('Brócoli congelado', 'congelados', '2 bolsas', 1),
  prod('Espinaca congelada', 'congelados', '1 bolsa', 1),
  prod('Papas a la francesa congeladas', 'congelados', '2 bolsas', 1),
  prod('Hamburguesas de res congeladas', 'congelados', '1 caja', 1),
  prod('Filetes de pescado empanizado congelados', 'congelados', '1 caja', 1),
  prod('Elote congelado', 'congelados', '1 bolsa'),
  prod('Chícharos con zanahoria congelados', 'congelados', '1 bolsa'),
  prod('Coliflor congelada', 'congelados', '1 bolsa'),
  prod('Ejotes congelados', 'congelados', '1 bolsa'),
  prod('Fresas congeladas', 'congelados', '1 bolsa'),
  prod('Mango congelado', 'congelados', '1 bolsa'),
  prod('Pizza congelada', 'congelados', '2 piezas'),
  prod('Hielo', 'congelados', '1 bolsa'),
  prod('Helado', 'congelados', '1 litro'),

  // Verduras y frutas que aguantan un mes bien guardadas
  prod('Papas', 'verduras', '3 kg', 1, 'Lugar fresco y oscuro, sin refrigerar'),
  prod('Cebolla', 'verduras', '1.5 kg', 1, 'Lugar fresco y seco, lejos de las papas'),
  prod('Ajo', 'verduras', '2 cabezas', 1),
  prod('Limones', 'verduras', '1 kg', 1, 'En el refri, en bolsa cerrada'),
  prod('Manzanas', 'verduras', '2 kg', 1, 'En el refri duran 4 semanas'),
  prod('Naranjas', 'verduras', '2 kg', 1, 'En el refri duran 3–4 semanas'),
  prod('Zanahorias', 'verduras', '1 kg', 0, 'En el refri duran 3 semanas'),
  prod('Camote', 'verduras', '1 kg'),
  prod('Plátanos', 'verduras', '6 piezas', 0, 'Solo para la primera semana'),
  prod('Aguacate', 'verduras', '3 piezas', 0, 'Compra verdes y ve madurándolos'),
  prod('Jitomate', 'verduras', '1 kg', 0, 'Dura 1 semana'),
  prod('Chiles serranos', 'verduras', '¼ kg'),
  prod('Pepino', 'verduras', '3 piezas'),
  prod('Lechuga', 'verduras', '1 pieza'),
  prod('Calabacitas', 'verduras', '½ kg'),
  prod('Champiñones frescos', 'verduras', '1 charola'),
  prod('Cilantro', 'verduras', '1 manojo'),
  prod('Uvas', 'verduras', '½ kg'),
  prod('Piña', 'verduras', '1 pieza'),
  prod('Papaya', 'verduras', '1 pieza'),

  // Lácteos (preferir los que duran más)
  prod('Leche larga vida', 'lacteos', '8 litros', 1, 'Sin abrir no necesita refri'),
  prod('Queso Oaxaca', 'lacteos', '1 kg', 1, 'Congela la mitad'),
  prod('Queso amarillo rebanado', 'lacteos', '2 paquetes', 1),
  prod('Queso parmesano', 'lacteos', '1 frasco', 1),
  prod('Mantequilla', 'lacteos', '1 barra', 1),
  prod('Queso manchego', 'lacteos', '½ kg'),
  prod('Queso panela', 'lacteos', '1 pieza', 0, 'Dura 2 semanas'),
  prod('Crema', 'lacteos', '1 frasco', 0, 'Dura 2 semanas abierta'),
  prod('Yogur', 'lacteos', '1 litro', 0, 'Dura 2–3 semanas cerrado'),
  prod('Leche en polvo', 'lacteos', '1 bote'),
  prod('Queso crema', 'lacteos', '1 barra'),
  prod('Margarina', 'lacteos', '1 bote'),

  // Tortillas y pan (se congelan)
  prod('Tortillas de maíz', 'panaderia', '2 kg', 1, 'Congela en paquetes de 10'),
  prod('Tortillas de harina', 'panaderia', '2 paquetes', 1, 'Congela uno'),
  prod('Pan de caja', 'panaderia', '2 bolsas', 1, 'Congela una; se tuesta directo'),
  prod('Pan para hamburguesa', 'panaderia', '1 bolsa', 1, 'Congela'),
  prod('Tostadas', 'panaderia', '2 paquetes', 1),
  prod('Bolillos', 'panaderia', '6 piezas', 0, 'Congela y caliéntalos en sartén'),
  prod('Pan integral', 'panaderia', '1 bolsa'),
  prod('Pan árabe', 'panaderia', '1 paquete'),

  // Alacena
  prod('Arroz', 'alacena', '3 kg', 1, 'Cocina 1 olla cada 3–4 días o congela porciones'),
  prod('Pasta', 'alacena', '6 paquetes', 1),
  prod('Sopa de fideo', 'alacena', '6 paquetes', 1),
  prod('Puré de papa instantáneo', 'alacena', '2 cajas', 1),
  prod('Aceite', 'alacena', '1 litro', 1),
  prod('Azúcar', 'alacena', '1 kg', 1),
  prod('Arroz de microondas', 'alacena', '6 sobres', 0, 'Para los días sin tiempo'),
  prod('Harina de trigo', 'alacena', '1 kg'),
  prod('Pan molido', 'alacena', '1 bolsa'),
  prod('Lentejas', 'alacena', '1 kg'),
  prod('Garbanzos secos', 'alacena', '1 kg'),
  prod('Sopa instantánea', 'alacena', '6 vasos'),
  prod('Macarrones con queso', 'alacena', '4 cajas'),
  prod('Tortillinas para nachos', 'alacena', '1 bolsa'),

  // Latas y conservas
  prod('Atún en lata', 'latas', '12 latas', 1),
  prod('Elote en lata', 'latas', '4 latas', 1),
  prod('Champiñones en lata', 'latas', '4 latas', 1),
  prod('Puré de tomate', 'latas', '8 cajas', 1),
  prod('Chiles chipotles en lata', 'latas', '2 latas', 1),
  prod('Chiles en vinagre', 'latas', '1 lata', 1),
  prod('Sardinas en tomate', 'latas', '4 latas'),
  prod('Salmón en lata', 'latas', '2 latas'),
  prod('Duraznos en almíbar', 'latas', '2 latas'),
  prod('Piña en almíbar', 'latas', '2 latas'),
  prod('Coctel de frutas', 'latas', '2 latas'),
  prod('Garbanzos en lata', 'latas', '2 latas'),
  prod('Ensalada de verduras en lata', 'latas', '2 latas'),
  prod('Aceitunas', 'latas', '1 frasco'),
  prod('Rajas en lata', 'latas', '2 latas'),
  prod('Leche evaporada', 'latas', '2 latas'),
  prod('Leche condensada', 'latas', '1 lata'),

  // Salsas y condimentos
  prod('Salsa de soya', 'salsas', '1 botella', 1),
  prod('Mayonesa', 'salsas', '1 frasco', 1),
  prod('Catsup', 'salsas', '1 botella', 1),
  prod('Mostaza', 'salsas', '1 botella', 1),
  prod('Salsa verde (frasco)', 'salsas', '2 frascos', 1),
  prod('Salsa picante', 'salsas', '1 botella', 1),
  prod('Caldo de res en cubo', 'salsas', '1 caja', 1),
  prod('Ajo en polvo', 'salsas', '1 frasco', 1),
  prod('Sal', 'salsas', '1 bote', 1),
  prod('Pimienta', 'salsas', '1 frasco', 1),
  prod('Orégano', 'salsas', '1 bolsa'),
  prod('Comino', 'salsas', '1 bolsa'),
  prod('Paprika', 'salsas', '1 frasco'),
  prod('Consomé en polvo', 'salsas', '1 frasco'),
  prod('Jugo Maggi', 'salsas', '1 botella'),
  prod('Salsa inglesa', 'salsas', '1 botella'),
  prod('Salsa BBQ', 'salsas', '1 botella'),
  prod('Vinagre', 'salsas', '1 botella'),
  prod('Jugo de limón embotellado', 'salsas', '1 botella', 0, 'Por si se acaban los limones'),
  prod('Aderezo ranch', 'salsas', '1 botella'),
  prod('Pesto', 'salsas', '1 frasco'),
  prod('Salsa de tomate para pasta', 'salsas', '2 frascos'),
  prod('Miel', 'salsas', '1 frasco'),

  // Desayuno y botanas
  prod('Avena', 'desayuno', '1 kg', 1),
  prod('Cereal', 'desayuno', '2 cajas', 1),
  prod('Café', 'desayuno', '1 frasco', 1),
  prod('Galletas', 'desayuno', '4 paquetes', 1),
  prod('Crema de cacahuate', 'desayuno', '1 frasco', 1),
  prod('Mermelada', 'desayuno', '1 frasco'),
  prod('Harina para hot cakes', 'desayuno', '1 caja'),
  prod('Granola', 'desayuno', '1 bolsa'),
  prod('Barras de cereal', 'desayuno', '1 caja'),
  prod('Cacahuates', 'desayuno', '1 bolsa'),
  prod('Papas fritas', 'desayuno', '3 bolsas'),
  prod('Palomitas de microondas', 'desayuno', '1 caja'),
  prod('Chocolate en polvo', 'desayuno', '1 bote'),
  prod('Té', 'desayuno', '1 caja'),
  prod('Pan dulce empacado', 'desayuno', '2 paquetes'),
  prod('Nueces o almendras', 'desayuno', '1 bolsa'),

  // Bebidas
  prod('Agua embotellada', 'bebidas', '1 garrafón por semana', 1),
  prod('Agua mineral', 'bebidas', '6 botellas'),
  prod('Refrescos', 'bebidas', '1 paquete'),
  prod('Jugo de caja', 'bebidas', '4 litros'),
  prod('Polvo para agua de sabor', 'bebidas', '10 sobres'),
  prod('Bebida deportiva', 'bebidas', '4 botellas'),
  prod('Cerveza', 'bebidas', '1 paquete'),

  // Aseo personal
  prod('Papel higiénico', 'aseoPersonal', '12 rollos', 1),
  prod('Jabón de baño', 'aseoPersonal', '4 barras', 1),
  prod('Shampoo', 'aseoPersonal', '1 botella', 1),
  prod('Pasta dental', 'aseoPersonal', '2 tubos', 1),
  prod('Desodorante', 'aseoPersonal', '1 pieza', 1),
  prod('Rastrillos', 'aseoPersonal', '1 paquete', 1),
  prod('Acondicionador', 'aseoPersonal', '1 botella'),
  prod('Cepillo de dientes', 'aseoPersonal', '1 pieza', 0, 'Cambiar cada 3 meses'),
  prod('Hilo dental', 'aseoPersonal', '1 pieza'),
  prod('Enjuague bucal', 'aseoPersonal', '1 botella'),
  prod('Espuma o gel para afeitar', 'aseoPersonal', '1 pieza'),
  prod('Crema corporal', 'aseoPersonal', '1 botella'),
  prod('Protector solar', 'aseoPersonal', '1 pieza'),
  prod('Jabón líquido para manos', 'aseoPersonal', '1 botella'),
  prod('Cotonetes', 'aseoPersonal', '1 caja'),
  prod('Pañuelos desechables', 'aseoPersonal', '1 caja'),
  prod('Gel para el cabello', 'aseoPersonal', '1 pieza'),
  prod('Cortaúñas', 'aseoPersonal', '1 pieza'),
  prod('Toallas femeninas', 'aseoPersonal', '1 paquete'),
  prod('Curitas', 'aseoPersonal', '1 caja'),
  prod('Paracetamol', 'aseoPersonal', '1 caja'),

  // Limpieza del hogar
  prod('Detergente para ropa', 'limpieza', '1 bolsa (3 kg)', 1),
  prod('Suavizante', 'limpieza', '1 botella', 1),
  prod('Lavatrastes', 'limpieza', '1 botella', 1),
  prod('Cloro', 'limpieza', '1 botella', 1),
  prod('Limpiador multiusos', 'limpieza', '1 botella', 1),
  prod('Bolsas de basura', 'limpieza', '1 rollo', 1),
  prod('Esponjas', 'limpieza', '3 piezas', 1),
  prod('Servilletas', 'limpieza', '2 paquetes', 1),
  prod('Bolsas para congelar (tipo ziploc)', 'limpieza', '1 caja', 1, 'Clave para guardar porciones'),
  prod('Papel aluminio', 'limpieza', '1 rollo', 1),
  prod('Plástico autoadherente', 'limpieza', '1 rollo'),
  prod('Toallas de papel', 'limpieza', '2 rollos'),
  prod('Fibras para trastes', 'limpieza', '2 piezas'),
  prod('Limpiador de pisos', 'limpieza', '1 botella'),
  prod('Limpiavidrios', 'limpieza', '1 botella'),
  prod('Desengrasante de cocina', 'limpieza', '1 botella'),
  prod('Pastillas para el baño', 'limpieza', '1 paquete'),
  prod('Aromatizante', 'limpieza', '1 pieza'),
  prod('Insecticida', 'limpieza', '1 pieza'),
  prod('Guantes de limpieza', 'limpieza', '1 par'),
  prod('Jerga o trapos', 'limpieza', '2 piezas'),
  prod('Focos', 'limpieza', '1 pieza'),
  prod('Pilas', 'limpieza', '1 paquete'),
  prod('Cerillos o encendedor', 'limpieza', '1 pieza'),
];

const CONSEJOS_MES = [
  'Al llegar del súper, divide la carne en porciones de una comida y congélalas en bolsas planas: se descongelan rápido.',
  'Pasa al refri la porción del día siguiente la noche anterior.',
  'Congela tortillas y pan en paquetes chicos; se calientan directo del congelador.',
  'Papas, cebolla y ajo aguantan un mes en un lugar fresco y oscuro (no juntes papa con cebolla).',
  'Limones, manzanas y naranjas duran 3–4 semanas en el cajón del refri.',
  'Cocina una olla de arroz cada 3–4 días, o congélalo en porciones.',
  'Si quieres algo fresco (plátano, aguacate, jitomate), cómpralo solo para la primera semana.',
];

const SNACKS = [
  { nombre: 'Manzana', kcal: 95 },
  { nombre: 'Naranja', kcal: 60 },
  { nombre: 'Plátano', kcal: 105 },
  { nombre: 'Yogur', kcal: 150 },
  { nombre: 'Pan dulce', kcal: 350 },
  { nombre: 'Café con leche', kcal: 120 },
  { nombre: 'Avena con leche', kcal: 250 },
  { nombre: 'Cereal con leche', kcal: 250 },
  { nombre: 'Pan con crema de cacahuate', kcal: 280 },
  { nombre: 'Refresco (lata)', kcal: 140 },
  { nombre: 'Galletas (4)', kcal: 200 },
  { nombre: 'Tortilla', kcal: 70 },
  { nombre: 'Cerveza', kcal: 150 },
  { nombre: 'Papas fritas (bolsa)', kcal: 230 },
];

const EXCLUSIONES_INICIALES = ['pollo', 'huevo', 'camarón', 'frijol'];

const DIAS = ['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado', 'Domingo'];
